apiVersion: apps/v1
kind: Deployment
metadata:
  name: docx-to-pdf-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docx-to-pdf
  template:
    metadata:
      labels:
        app: docx-to-pdf
    spec:
      containers:
        - name: backend
          image: docx-to-pdf-backend:latest
          ports:
            - containerPort: 5000
        - name: frontend
          image: docx-to-pdf-frontend:latest
          ports:
            - containerPort: 3000
