apiVersion: v1
kind: Service
metadata:
  name: docx-to-pdf-service
spec:
  type: LoadBalancer
  selector:
    app: docx-to-pdf
  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
